--- #YAML:1.0
name:                WebService-Aladdin
version:             0.01
abstract:            ~
license:             ~
author:              
    - JEEN <jeen@perl.kr>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Class::Accessor::Fast:         0
    LWP::UserAgent:                0
    Test::Base:                    0
    URI:                           0
    version:                       0
    XML::FeedPP:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
