---
abstract: 'Aladdin WebService API Module'
author:
  - 'JEEN <jeen@perk_dot_kr>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Aladdin
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  LWP::UserAgent: 0
  Test::Base: 0
  URI: 0
  XML::FeedPP: 0
  version: 0
resources:
  repository: git://github.com/JEEN/p5-WebService-Aladdin.git
version: 0.0706
